import pprint

NEWS_PASSAGE1 = """ Bell Canada is alerting customers after hackers illegally
accessed the information of fewer than 100,000 customers, the telecom giant
told CBC News.

The breach comes just eight months after 1.9 million customer emails were
stolen from Bell's database by an anonymous hacker.

Bell is Canada's largest telecom company, with over 22 million customers.

The information obtained in the latest breach included details such as names,
email addresses, account user names and numbers, as well as phone numbers.

Bell said there was no indication that credit card, banking or other
information was accessed.

But, it would not say when the breach took place or whether it was related to
a past incident.

"We apologize to our customers and are contacting all those affected," said
Bell spokesperson Marc Choma in an email.

Bell added that it had notified appropriate government agencies including the
Office of the Privacy Commissioner of Canada.

"Bell works closely with law enforcement, government and the broader
technology industry to combat the growth of cybercrimes, and we have
successfully supported law enforcement in past prosecutions of hackers,"
Choma said.

Ongoing investigation Tobi Cohen, a spokesperson for the Office of the
Privacy Commissioner, confirmed in an email that Bell had notified it of the
breach and that it is following up with the company to get more information
and "determine follow up actions."

The RCMP is also investigating.

Chester Wisniewski, an expert at the data security firm Sophos Canada, said
the breach did make customers more likely to be victimized by potential
phishing attacks; as seen in other big breaches like those at LinkedIn and
Ashley Madison.

AshleyMadison security protocols violated privacy laws, watchdog says "When
you see email addresses leaked, that's a really goodthing for spammers and
phishing attacks through email, because they know that if you're in Bell's
database, you likely to have some sort of commercial relationship with Bell,"
he said.

"So, they can send you one of those fake emails saying, 'Hey your cell phone
bill is due, click here to login.'"

Wisniewski added that Bell was under no legal obligation to notify customers
of the breach, because stolen email addresses are not considered personally
identifiable such as a driver's licence or social insurance number.

"A lot of times when companies lose this kind of information, they don't even
tell you," he said. "The good thing about them telling us is to put us on
alert for those types of things now."

A person or group claiming to be behind the attack against Bell in May warned
in an online post that more data would be leaked if Bell did not co-operate."""

NEWS_PASSAGE2 = """ Coastal communities in British Columbia and Alaska were
evacuated to higher ground early this morning after tsunami warning sirens
blared following a large earthquake off the coast of Alaska. But the warning
was later cancelled without any reported tsunami damage. Why?

Tsunamis are giant waves — up to 30 metres high — generated by large
earthquakes, and can cause massive damage. The 2004 Boxing Day tsunami in the
Indian Ocean killed more than 200,000 people. More recently, a massive
earthquake and tsunami in Japan in 2011, caused major damage and a meltdown
at the Fukushima nuclear power plant.

Tuesday's earthquake struck at 1:31 a.m. PT in the Pacific Ocean about 250
kilometres southeast of Chiniak, Alaska. The U.S. Geological Survey initially
reported the quake's strength at 8.2 and later revised that to 7.9, with a
depth of 25 kilometres. At least three aftershocks were reported.

Earth is comprised of moving slabs of rock called plates. Areas where they
meet are called fault lines. When these move against each other we get
earthquakes.

According to the International Tsunami Information Centre, the most
destructive tsunamis are generated from large, shallow earthquakes — those
with a magnitude higher than 7.5 and less than 70 kilometres deep — with an
epicentre or fault line near or on the ocean floor.

Tuesday's earthquake met those criteria.

But the type of earthquake also matters, reports CBC seismologist Johanna
Wagstaffe.

She said the quake struck in an area where there is a transition between two
types of earthquakes:

Strike-slip, where two tectonic plates slide horizontally past each other.
Megathrust, where one plate slides under the other, also called subduction.
"This kind of earthquake was what is called a strike-slip earthquake,"
Wagstaffe said. "That means there isn't as much vertical displacement. So
when you're thinking of these rocks on the ocean floor, it didn't punch up
like some other earthquakes have."

Instead of the water being displaced upward and forward, this water was moved
much less by the horizontal motion. A fortunate circumstance for anyone
living along the coast.

In the case of the 2004 and 2011 earthquakes, there was more vertical motion,
which had devastating consequences. Roughly 225,000 were killed in the 2004
earthquake; 20,000 people were killed in Japan in 2011.

Motion of the plates 

The West Coast is an area with quite a few fault lines
that can result in various motions, Wagstaffe explains.

"Where the Gulf of Alaska curves, you end up getting a splay of fault lines,"
she said. "There's a really interesting section where this earthquake
occurred where you can get all different kinds of motion happening. If it
had've occurred 90 kilometres to the west then it would have been a
subduction earthquake and we could have seen a massive tsunami."

And it's not without precedent.

On March 27, 1964, a 9.2 magnitude earthquake occurred off the coast of
Alaska at a depth of 25 kilometres. Rather than being a strike-slip, it was a
megathrust and produced a tsunami that rose 30 metres in some areas, killing
more than 130 people.

"This is a reminder that we live in a seismically active area of the world.…
It's also a reminder that we get different kinds. We're waiting for the 'Big
One,' but we could also get a smaller earthquake, shallower closer to a major
city. That would be devastating."

Wagstaffe said the West Coast can expect after shocks over the next few days
or even weeks.

For now, seismologists will gather data collected from the earthquake to
better understand the risks along the West Coast.

"We are quite vulnerable to a lot of different earthquake risks here."

"""

def remove_punctuation(passage):
    punctuation = ".", "'", '"', ";", ":", ",", "?"

    # Remove punctation from passage
    for i in punctuation:
        passage = passage.replace(i, " ")

    return passage

# generate word list function from the list activity
# remove all of the punctuation from each passage 

# split each passage into a list of words

# create list of unique words based on the raw word list for passage 1
# create a set for passage 1 from the list of unique words

# create list of unique words based on the raw word list for passage 2
# create a set for passage 2 from the list of unique words

# create a set of words that are in both passage 1 and passage 2

# Use pprint.pprint to print a list of words that is in both passage 1 and passage 2